from . import auto_info_birthday
from . import adminpost
from . import birthday_handlers
from . import help
from . import infoBirthday
from . import sozlamalar
from . import support
from . import start
from . import gr_auot_info